#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=paragraph_extraction
#SBATCH --mail-user=ashkank@umich.edu
#SBATCH --mail-type=BEGIN,END
#SBATCH --time=48:00:00
#SBATCH --account=mihalcea
#SBATCH --gres=gpu:2
#SBATCH --partition=gpu
#SBATCH --output=/home/ashkank/logs/%x-%j.log
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=8g

# The application(s) to execute along with its input arguments and options:
cd /home/ashkank/
source .bashrc
cd QAforMisinformation
conda activate QAforMisinfo
cd paragraph_ranking/
python paragraph_relevance_classification.py 1 label
python paragraph_relevance_classification.py 2 label
python paragraph_relevance_classification.py 3 label
python paragraph_relevance_classification.py 4 label
python paragraph_relevance_classification.py 5 label
python paragraph_relevance_classification.py 6 label
python paragraph_relevance_classification.py 7 label
python paragraph_relevance_classification.py 8 label
python paragraph_relevance_classification.py 9 label
python paragraph_relevance_classification.py 10 label