#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=test_job_ash
#SBATCH --mail-user=ashkank@umich.edu
#SBATCH --mail-type=BEGIN,END
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=1000m
#SBATCH --time=10:00
#SBATCH --account=mihalcea
#SBATCH --partition=gpu

# The application(s) to execute along with its input arguments and options:
echo "Hello World from Great Lakes" > alaki.log
