#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=qa-binary
#SBATCH --mail-user=ashkank@umich.edu
#SBATCH --mail-type=BEGIN,END
#SBATCH --time=05:00:00
#SBATCH --account=mihalcea1
#SBATCH --gres=gpu:2
#SBATCH --partition=gpu
#SBATCH --output=/home/ashkank/logs/%x-%j.log
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=8g

# The application(s) to execute along with its input arguments and options:
cd /home/ashkank/
source .bashrc
cd QAforMisinformation
conda activate QAforMisinfo
cd qa/
python qa_xlnet_long_doc.py 1